import { Team } from './team';

export const TEAMS: Team[] = [
    { id: 1, name: 'Atlanta Hawks', logo: 'assets/img/hawks.svg' },
    { id: 2, name: 'Boston Celtics', logo: 'assets/img/celtics.svg' },
    { id: 3, name: 'Brooklyn Nets', logo: 'assets/img/nets.svg' },
    { id: 4, name: 'Charlotte Hornets', logo: 'assets/img/hornets.svg' },
    { id: 5, name: 'Chicago Bulls', logo: 'assets/img/bulls.svg' },
    { id: 6, name: 'Cleveland Cavaliers', logo: 'assets/img/cavaliers.svg' },
    { id: 7, name: 'Dallas Mavericks', logo: 'assets/img/marvericks.svg' },
    { id: 8, name: 'Denver Nuggets', logo: 'assets/img/nuggets.svg' },
    { id: 9, name: 'Detroit Pistons', logo: 'assets/img/pistons.svg' },
    { id: 10, name: 'Golden State Warriors', logo: 'assets/img/warriors.svg' },
    { id: 11, name: 'Houston Rockets', logo: 'assets/img/rockets.svg' },
    { id: 12, name: 'Indiana Pacers', logo: 'assets/img/pacers.svg' },
    { id: 13, name: 'LA Clippers', logo: 'assets/img/clippers.svg' },
    { id: 14, name: 'Los Angeles Lakers', logo: 'assets/img/lakers.svg' },
    { id: 15, name: 'Memphis Grizzlies', logo: 'assets/img/grizzlies.svg' },
    { id: 16, name: 'Miami Heat', logo: 'assets/img/heat.svg' },
    { id: 17, name: 'Milwaukee Bucks', logo: 'assets/img/bucks.svg' },
    { id: 18, name: 'Minnesota Timberwolves', logo: 'assets/img/timberwolves.svg' },
    { id: 19, name: 'New Orleans Pelicans', logo: 'assets/img/pelicans.svg' },
    { id: 20, name: 'New York Knicks', logo: 'assets/img/knicks.svg' },
    { id: 21, name: 'Oklahoma City Thunder', logo: 'assets/img/thunder.svg' },
    { id: 22, name: 'Orlando Magic', logo: 'assets/img/magic.svg' },
    { id: 23, name: 'Philadelphia 76ers', logo: 'assets/img/76ers.svg' },
    { id: 24, name: 'Pheonix Suns', logo: 'assets/img/suns.svg' },
    { id: 25, name: 'Portland Trail Blazers', logo: 'assets/img/blazers.svg' },
    { id: 26, name: 'Sacremento Kings', logo: 'assets/img/kings.svg' },
    { id: 27, name: 'San Antonio Spurs', logo: 'assets/img/spurs.svg' },
    { id: 28, name: 'Toronoto Raptors', logo: 'assets/img/raptors.svg' },
    { id: 29, name: 'Utah Jazz', logo: 'assets/img/jazz.svg' },
    { id: 30, name: 'Washington Wizards', logo: 'assets/img/wizards.svg' }
];